"""Add tropical nights columns

Revision ID: 973b76508640
Revises: 
Create Date: 2025-01-22 01:16:49.885697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '973b76508640'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('district', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tropical_nights_current', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tropical_nights_future', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('district', schema=None) as batch_op:
        batch_op.drop_column('tropical_nights_future')
        batch_op.drop_column('tropical_nights_current')

    # ### end Alembic commands ###
